# Generated by Django 4.0.4 on 2022-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
        ),
    ]
