# Generated by Django 4.0.4 on 2022-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_book_book_cover_author_portrait_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='portrait',
            field=models.ImageField(default='defaultPortrait.png', upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='defaultCover.png', upload_to='covers/'),
        ),
    ]
