# Generated by Django 4.0.4 on 2022-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_author_portrait_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default='N/A', help_text='Price in US Dollar', max_length=3),
        ),
    ]
