# Generated by Django 4.0.4 on 2022-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='books',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='books',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
