# Generated by Django 4.0.4 on 2022-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_shoppingcart_books_shoppingcart_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='books',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='books',
            field=models.ManyToManyField(to='app.book'),
        ),
    ]
