# Generated by Django 4.0.4 on 2022-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_author_options_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bigraphy',
            field=models.TextField(default='', help_text='Enter a brief bigraphy of the author', max_length=1000),
        ),
    ]
