# Generated by Django 4.0.4 on 2022-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_author_bigraphy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bigraphy',
            field=models.TextField(help_text='Enter a brief bigraphy of the author', max_length=1000),
        ),
    ]
