# Generated by Django 4.0.4 on 2022-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_author_bigraphy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bigraphy',
        ),
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(default='', help_text='Enter a brief biography of the author', max_length=1000),
            preserve_default=False,
        ),
    ]
