# Generated by Django 4.0.4 on 2022-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_comment_comment_text_comment_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recommend',
            field=models.CharField(choices=[('I Dont Recommend It', 'I Dont Recommend It'), ('Not Sure To Recommend', 'Not Sure To Recommend'), ('I Recommend It', 'I Recommend It')], max_length=50),
        ),
    ]
