# Generated by Django 4.0.4 on 2022-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_comment_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
